#!/usr/bin/env python3
"""Generate src/gen/statusdata.h: Keen font glyphs as NES bg CHR for the
status screen (Select overlay), pinned to the LAST 2KB of CHR ROM.

The font is EGAGRAPH chunk 3 (1bpp, 8px rows). The bytes are identical in
Keen 4 and Keen 6 (md5 6442e234212a670a631d23c84ce7807a), so ONE generated
header serves both episodes; the CHR bank number differs per episode only
through TOTAL_CHR_KB, handled with a preprocessor chain in the header.

Placement: the SDK linker script (nes-mmc3 common.ld) defines a 1KB memory
region + input section per CHR bank (.chr_rom_N). Emitting into
.chr_rom_(TOTAL_CHR_KB-2) puts the glyphs in the power-of-two padding tail
of CHR ROM, far above the sequential .chr_rom section that leveldata.c
(level+sprite CHR) and titledata.c (.chr_rom.title) fill upward — keen4
uses 61 of 64KB, keen6 85 of 128KB. If those ever grow into the tail the
linker fails loudly with an overlap error. The bank index is even, as the
2KB bg CHR window requires.

Glyph set: ASCII 32..90 (space..'Z'), tile index = ch - 32, 59 tiles,
944 bytes; color 3 (both planes set) so bg palette color 3 is the text
color. Tile 0 = space = blank.

Invoked by the Makefile per-episode recipe; can also be run manually
(any KEEN_EP with extracted assets):
    KEEN_EP=4 .venv/bin/python tools/gen_status.py
MIT License; see LICENSE.
"""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import keenlib as K

ROOT = Path(__file__).parent.parent
GEN = ROOT / "src" / "gen"
GEN.mkdir(parents=True, exist_ok=True)

FONT_MD5 = "6442e234212a670a631d23c84ce7807a"

GLYPH_LO = 32   # ' '
GLYPH_HI = 90   # 'Z'


def main():
    ega = K.EgaGraph()
    font = ega.chunk(3)
    import hashlib
    md5 = hashlib.md5(font).hexdigest()
    if md5 != FONT_MD5:
        print(f"WARNING: font chunk md5 {md5} != known {FONT_MD5};"
              " keen4/keen6 header sharing assumption may be broken")

    fheight = struct.unpack_from("<H", font)[0]
    foffs = struct.unpack_from("<256H", font, 2)
    fwidths = font[514:514 + 256]

    tiles = []
    for c in range(GLYPH_LO, GLYPH_HI + 1):
        wb = (fwidths[c] + 7) // 8
        lo = bytearray(8)
        for y in range(min(8, fheight)):
            if wb:
                lo[y] = font[foffs[c] + y * wb]
        tiles.append(bytes(lo) + bytes(lo))  # color 3 (planes identical)

    blob = b"".join(tiles)
    n = len(blob)
    assert n <= 1024, "glyphs must fit one 1KB CHR bank"

    lines = []
    lines.append("// generated by tools/gen_status.py — Keen status-screen"
                 " font CHR.\n")
    lines.append("// Identical for Keen 4 and Keen 6 (EGAGRAPH chunk 3);"
                 " the CHR bank is\n")
    lines.append("// the last even 1KB pair of the padded CHR ROM"
                 " (TOTAL_CHR_KB - 2).\n")
    lines.append("#ifndef GEN_STATUSDATA_H\n#define GEN_STATUSDATA_H\n")
    lines.append("#include \"levels.h\"\n")
    first = True
    for total in (32, 64, 128, 256, 512):
        kw = "#if" if first else "#elif"
        first = False
        page = total - 2
        lines.append(f"{kw} TOTAL_CHR_KB == {total}\n")
        lines.append(f"#define STATUS_CHR_BANK {page & 255}\n")
        lines.append(f"#define STATUS_CHR_UPPER {page >> 8}\n")
        lines.append(f"#define STATUS_CHR_SECTION \".chr_rom_{page}\"\n")
    lines.append("#else\n#error gen_status.py: unhandled TOTAL_CHR_KB\n")
    lines.append("#endif\n")
    lines.append(f"#define STATUS_GLYPH_LO {GLYPH_LO}\n")
    lines.append("// tile index of char c: c - STATUS_GLYPH_LO"
                 " (space..'Z'); tile 0 blank\n")
    lines.append("__attribute__((used, section(STATUS_CHR_SECTION)))\n")
    lines.append(f"static const unsigned char status_font_chr[{n}] = {{\n")
    for i in range(0, n, 16):
        lines.append("  " + ",".join(str(b) for b in blob[i:i + 16]) + ",\n")
    lines.append("};\n")
    lines.append("#endif\n")
    (GEN / "statusdata.h").write_text("".join(lines))
    print(f"statusdata.h: {len(tiles)} glyph tiles, {n} bytes CHR,"
          f" section .chr_rom_(TOTAL_CHR_KB-2)")


if __name__ == "__main__":
    main()
