#!/usr/bin/env python3
"""Convert extracted PC-speaker sound effects to NES APU pulse data.

PC speaker format (id Sound Manager): uint32 length, uint16 priority, then
one byte per 1/140s tick; 0 = silence, else PIT divisor = value * 60, i.e.
frequency = 1193182 / (60 * value).

NES pulse period = 1789773 / (16 * freq) - 1, 11 bits. We pre-convert every
tick to a period word (0 = silence) so the runtime driver is trivial.
Emits src/gen/sfx.c / sfx.h.
"""
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import os
EP = int(os.environ.get("KEEN_EP", "6"))
AUD = ROOT / f"assets/extracted/ck{EP}/audio"
GEN = ROOT / "src/gen"
GEN.mkdir(parents=True, exist_ok=True)

# sound number -> C name. Numbers are the game's own SOUND_* audio IDs.
SOUNDS = {
    2: "JUMP", 3: "LAND", 4: "SHOOT", 7: "POGO", 8: "ITEM",
    9: "AMMO",          # SOUND_GOTSTUNNER (ammo pickup)
    13: "LEVELDONE",    # SOUND_LEVELEXIT (level complete)
    14: "KEYCARD",      # SOUND_NEEDKEYCARD (locked security door)
    17: "EXTRALIFE", 18: "OPENGEMDOOR", 19: "GEM", 21: "NOAMMO",
    23: "DIE", 25: "SHOTHIT",
}
# Only sounds actually triggered are included (each costs SFX-bank space).
# Enemy sounds (WORMMOUTHBITE 5, MUSHROOMLEAP 16, SKYPESTSQUISH 22 ...) are
# omitted: the constant ones would keep interrupting the pulse-2 music channel.
# keen4 has no flagpole so SOUND_FLAGFLIP 43 doesn't apply.

PIT_CLOCK = 1193182
NES_CLOCK = 1789773


def convert(num):
    data = (AUD / f"sfx_pc_{num:02d}.bin").read_bytes()
    length, _prio = struct.unpack_from("<IH", data, 0)
    ticks = data[6:6 + length]
    periods = []
    for v in ticks:
        if v == 0:
            periods.append(0)
        else:
            freq = PIT_CLOCK / (60 * v)
            p = round(NES_CLOCK / (16 * freq)) - 1
            periods.append(max(8, min(p, 0x7FF)))
    return periods


def main():
    src = ["// generated by gen_sfx.py\n"]
    hdr = ["#ifndef GEN_SFX_H\n#define GEN_SFX_H\n"]
    table_ptr = []
    table_len = []
    for i, (num, name) in enumerate(sorted(SOUNDS.items())):
        p = convert(num)
        src.append(f'__attribute__((used, section(".prg_rom_8"))) '
                   f"const unsigned short sfx_{name}[{len(p)}] = "
                   f"{{ {', '.join(str(x) for x in p)} }};\n")
        table_ptr.append(f"sfx_{name}")
        table_len.append(len(p))
        hdr.append(f"#define SFX_{name} {i}\n")
    src.append('__attribute__((used, section(".prg_rom_8"))) '
               "const unsigned short *const sfx_data[] = { "
               + ", ".join(table_ptr) + " };\n")
    src.append('__attribute__((used, section(".prg_rom_8"))) '
               "const unsigned short sfx_len[] = { "
               + ", ".join(str(l) for l in table_len) + " };\n")
    hdr.append("extern const unsigned short *const sfx_data[];\n")
    hdr.append("extern const unsigned short sfx_len[];\n#endif\n")
    (GEN / "sfx.c").write_text("".join(src))
    (GEN / "sfx.h").write_text("".join(hdr))
    print("sfx:", {SOUNDS[n]: len(convert(n)) for n in sorted(SOUNDS)})


if __name__ == "__main__":
    main()
